services:
  extra_quiz:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
    expose:
      - 3000
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    networks:
      traefik_traefik:
        aliases:
          - grafana
networks:
  traefik_traefik:
      external: true